# This is a basic workflow to help you get started with Actions

name: scan

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Pulse-Pull-Image:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Docker pull
        run:  |
          docker login quay.io -u rianand -p ${{ secrets.MY_TOKEN }}
          docker pull quay.io/nvidia/pulse:rianand
      - name: code checkout
        uses: actions/checkout@v2
      - name: Test Pulse image
        run: |
          mkdir artifacts/
          PROJECTS=$(mvn -am dependency:tree | grep maven-dependency-plugin | awk '{ out="com.nvidia:"$(NF-1);print out }' | grep rapids | xargs | sed -e 's/ /,/g')    
          echo detect.maven.build.command="-pl=$PROJECTS -am" >> ./artifacts/application.properties
          chmod o+w ./artifacts/
          docker run --rm -i -v $GITHUB_WORKSPACE:/src/ -w /src/artifacts/ quay.io/nvidia/pulse:rianand pulse --no-clean --log-level debug --api-token ${PULSE_API_TOKEN} scan --build --project ${PULSE_SCAN_PROJECT} --project-version ${PULSE_SCAN_PROJECT_VERSION} --vulnerability-report ./scan_reports --fail /src/
          ls -l
        env:
          PULSE_API_TOKEN: ${{ secrets.TOKEN }}
          PULSE_SCAN_PROJECT: "test-project"
          PULSE_SCAN_PROJECT_VERSION: "v1"
      - name: Upload scan reports in Artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: /scan_reports

  
